import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/rootHeader";
import Footer from "@/components/layout/rootFooter";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const metadata = {
  title: "BRAC Bank | Leading Private Commercial Bank in Bangladesh",
  description:
    "Bangladesh’s most trusted private commercial bank. Working towards poverty free future with innovation.",
  keywords:
    "BRAC Bank, SME banking Bangladesh, digital banking Bangladesh, retail banking, savings account, SME loan, fixed deposit, online banking, sustainable banking, financial inclusion, Credit Card, Auto Loan, Car Loan, Home Loan",
  authors: [{ name: "BRAC Bank Limited" }],
  creator: "BRAC Bank Limited",
  language: "en",
  alternates: {
    canonical: `https://www.bracbank.com/en`,
    languages: {
      en: "https://www.bracbank.com/en",
      bn: "https://www.bracbank.com/bn",
    },
  },
  // Open Graph (Social Media)
  openGraph: {
    title: "BRAC Bank | Leading Private Commercial Bank in Bangladesh",
    description:
      "Bangladesh’s most trusted private commercial bank. Working towards poverty free future with innovation.",
    url: "https://www.bracbank.com",
    siteName: "BRAC Bank",
    images: [
      {
        url: "https://brackweb.s3.ap-southeast-1.amazonaws.com/uploads/all/og-image.69073c9258450.jpg",
        width: 1200,
        height: 630,
        alt: "BRAC Bank",
      },
    ],
    locale: "en_US",
    type: "website",
  },
  // Twitter Card
  twitter: {
    card: "summary_large_image",
    title: "BRAC Bank | Leading Private Commercial Bank in Bangladesh",
    description:
      "Bangladesh’s most trusted private commercial bank. Working towards poverty free future with innovation.",
    images: [
      "https://brackweb.s3.ap-southeast-1.amazonaws.com/uploads/all/og-image.69073c9258450.jpg",
    ],
  },
  // Additional Meta Tags
  other: {
    language: "English",
    "theme-color": "#007bff",
  },
  robots: {
    index: true,
    follow: true,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar/>
        <div className="bg-white min-h-screen">
        {children}

        </div>
        <Footer/>
      </body>
    </html>
  );
}
